logging:
  file:
    name: /home/job-opening-service/logs/JobOpeningService.log
  level:
    root: WARN

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

spring:
  application:
    name: jobopening
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${JOB_OPENING_DATABASE_HOSTNAME}:3306/${JOB_OPENING_DATABASE_NAME}
    username: ${JOB_OPENING_DATABASE_USER}
    password: ${JOB_OPENING_DATABASE_PASSWORD}
    hikari:
      initialization-fail-timeout: -1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect