version: "3.8"
services:
  job-opening-database:
    image: mysql:latest
    expose:
      - 3306
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d
      - job-opening-database-data:/var/lib/mysql
    env_file:
      - ./.database-env
    networks: 
      - ats-network
  job-opening-service:
    image: miniats/job-opening-service:latest
    expose: 
      - 8080
    volumes:
      - /tmp:/home/job-opening-service/logs
    env_file:
      - ./.job-opening-env
      - ./.discovery-env
    depends_on:
      - job-opening-database
    networks: 
      - ats-network
volumes:
  job-opening-database-data:
networks:
  ats-network:
    external:
      name: mini-ats-network
